### PR TITLE
changed build script and committed dist files

### PR DESCRIPTION
**Pull request by zwiebelspaetzle**
I've changed the build script so that it puts all needed files in dist.  I'm sure there's a sleeker way to do it with webpack.

### CODE REVIEW

**Review by fuhton — COMMENTED** [review]
Wow this is really great! Ideally we'll keep all dist files out of Github and added directly into NPM (hence the difference in the `.gitignore` and the `.npmignore`). That way the only tracked files in Github are source files, while NPM will have knowledge of dist files. 

I'd suggest un-committing the dist files and maybe changing the flag in the `.gitignore` to ignore _ALL_ dist files. 

Let me know if that makes sense!

**Comment by zwiebelspaetzle** [comment]
@fuhton sorry about the delay.  I've updated this PR to remove the dist directory from tracking, and added dist to .gitignore.

Please forgive my inexperience with publishing NPM packages, but how do the dist files end up in NPM if they're not in the repo?  Does NPM not pull the files directly from github?

Thanks!

**Comment by fuhton** [comment]
@zwiebelspaetzle Sorry for the delay in the response back!

We'll want to keep the `dist/.gitkeep` file and remove the `package-lock.json`.

The `.npmignore` does not ignore the dist files so we can publish those directly to NPM without having to keep track of them in Github. Let me know if that makes sense!

**Comment by zwiebelspaetzle** [comment]
Thanks for the feedback.  Please see the changes.

Even though `dist/.gitkeep` is in an ignored directory, I believe git will continue tracking it because it's been manually added.  Please let me know if I'm mistaken.

Thanks!

**Review by fuhton — APPROVED** [review]

**Pull request merged**
